import turtle
import random


screen = turtle.Screen()
t = turtle.Turtle()

t.speed(10)
t.hideturtle()


def japan():
    t.pu()
    t.goto(150, 100)
    t.lt(180)
    t.pd()
    t.color("black")

    for i in range(2):
        t.fd(300)
        t.lt(90)
        t.fd(200)
        t.lt(90)

    t.pu()
    t.goto(0, 50)
    t.pd()
    t.color("red")
    t.begin_fill()
    t.circle(50)
    t.end_fill()

    t.pu()
    t.color("white")
    t.goto(310, 0)

def poland():
    t.color("black")
    t.pu()
    t.goto(200, 0)
    t.pd()
    for i in range(2):
        t.lt(90)
        t.fd(125)
        t.lt(90)
        t.fd(400)
    t.color("red")
    t.begin_fill()
    for i in range(2):
        t.rt(90)
        t.fd(125)
        t.rt(90)
        t.fd(400)
    t.end_fill()

    t.color("white")
    t.pu()
    t.goto(500, 0)

def austria():
    t.color("black")
    t.penup()
    t.goto(150, 33)
    t.pd()
    t.lt(180)
    for i in range(2):
        t.fd(300)
        t.lt(90)
        t.fd(66)
        t.lt(90)
    t.pu()
    t.color("red")
    t.goto(150, -34)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(300)
        t.lt(90)
        t.fd(66)
        t.lt(90)
    t.end_fill()

    t.pu()
    t.goto(150, 99)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(300)
        t.lt(90)
        t.fd(65)
        t.lt(90)
    t.end_fill()

    t.pu()
    t.color("white")
    t.goto(300, -34)

def italy():
    t.color("green")
    t.begin_fill()
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.color("black", "white")
    t.begin_fill()
    t.right(90)
    t.fd(200)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.end_fill()


    t.begin_fill()
    t.right(90)
    t.fd(200)
    t.color("red")
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.end_fill()

def france():
    t.color("blue")
    t.begin_fill()
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.color("black", "white")
    t.begin_fill()
    t.right(90)
    t.fd(200)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.begin_fill()
    t.right(90)
    t.fd(200)
    t.color("red")
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.right(90)
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.end_fill()

def norway():
    t.color("black", "red")
    t.begin_fill()
    for i in range(4):
        t.fd(60)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(0, -100)
    t.pd()
    t.begin_fill()
    for i in range(4):
        t.fd(60)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(100, 0)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(60)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(100, -100)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(120)
        t.rt(90)
        t.fd(60)
        t.rt(90)
    t.end_fill()

    t.color("blue", "blue")
    t.pu()
    t.goto(70, 0)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(20)
        t.rt(90)
        t.fd(160)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(0, -70)
    t.pd()
    t.begin_fill()
    for i in range(2):
        t.fd(220)
        t.rt(90)
        t.fd(20)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(0, 0)
    t.pencolor("black")
    t.pd()
    for i in range(2):
        t.fd(220)
        t.rt(90)
        t.fd(160)
        t.rt(90)

def ukraine():
    t.color("blue")
    t.penup()
    t.begin_fill()
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.rt(90)
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.pendown()
    t.end_fill()

    t.goto(0, -100)
    t.color("yellow")
    t.penup()
    t.begin_fill()
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(100)
    t.rt(90)
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.pendown()
    t.end_fill()

def germany():
    t.color("yellow")
    t.begin_fill()
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.color("red")
    t.begin_fill()
    t.left(90)
    t.fd(66)
    t.left(90)
    t.fd(300)
    t.left(90)
    t.fd(66)
    t.left(90)
    t.fd(300)
    t.end_fill()
    t.pu()
    t.right(90)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(120)
    t.right(90)
    t.pd()
    t.color("black")
    t.begin_fill()
    t.fd(300)
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.end_fill()

def bahamas():
    t.color("#FDDA25")
    t.pu()
    t.goto(-200, 33)
    t.pd()

    t.begin_fill()
    for i in range(2):
        t.fd(400)
        t.rt(90)
        t.fd(66)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.color("#00A9CE")
    t.goto(-200, 99)
    t.pd()

    t.begin_fill()
    for i in range(2):
        t.fd(400)
        t.rt(90)
        t.fd(66)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.goto(-200, -33)
    t.pd()

    t.begin_fill()
    for i in range(2):
        t.fd(400)
        t.rt(90)
        t.fd(66)
        t.rt(90)
    t.end_fill()

    t.pu()
    t.color("black")
    t.goto(-200, 99)
    t.pd()

    t.begin_fill()
    t.goto(-40, 0)
    t.goto(-200, -99)
    t.end_fill()

    t.pu()
    t.color("white")
    t.goto(-600, -33)

def tanzania():
    t.color("#18B637")
    t.begin_fill()
    for i in range(2):
        t.fd(288)
        t.rt(90)
        t.fd(192)
        t.rt(90)
    t.end_fill()

    t.color("#00A5DE")
    t.pu()
    t.goto(0, -192)
    t.pd()
    t.begin_fill()
    t.goto(288, -192)
    t.goto(288, 0)
    t.goto(0, -192)
    t.end_fill()

    t.color("#FCD20E")
    t.pu()
    t.goto(0, -192)
    t.pd()
    t.begin_fill()
    t.goto(70, -192)
    t.goto(288, 0)
    t.goto(218, 0)
    t.goto(0, -192)
    t.end_fill()

    t.color("#000000")
    t.pu()
    t.goto(12, -192)
    t.pd()
    t.begin_fill()
    t.goto(58, -192)
    t.goto(276, 0)
    t.goto(230, 0)
    t.goto(12, -192)
    t.end_fill()

def russia():
    t.color("black", "white")
    t.begin_fill()
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.end_fill()
    t.pendown()

    t.goto(0, -80)
    t.color("blue")
    t.penup()
    t.begin_fill()
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.end_fill()
    t.pendown()

    t.goto(0, -160)
    t.color("red")
    t.penup()
    t.begin_fill()
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(80)
    t.end_fill()

def kuwait():
    t.color("red")
    t.begin_fill()
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.color("black", "white")
    t.begin_fill()
    t.left(90)
    t.fd(66)
    t.left(90)
    t.fd(300)
    t.left(90)
    t.fd(66)
    t.left(90)
    t.fd(300)
    t.end_fill()
    t.pu()
    t.right(90)
    t.right(90)
    t.fd(300)
    t.right(90)
    t.fd(120)
    t.right(90)
    t.pd()
    t.color("green")
    t.begin_fill()
    t.fd(300)
    t.right(90)
    t.fd(66)
    t.right(90)
    t.fd(300)
    t.end_fill()

    t.pu()
    t.right(90)
    t.fd(66)
    t.right(135)
    t.pd()
    t.color("black")
    t.begin_fill()
    t.fd(90)
    t.left(315)
    t.fd(55)
    t.left(317)
    t.fd(95)
    t.left(222)
    t.fd(200)
    t.end_fill()


# ftiaxnete tin guala me oles tis simaies mesa
flags = [japan, poland, austria, italy, france, norway, ukraine, germany, bahamas, tanzania, russia, kuwait]
points = 0
lives = 3
hints = 3
w = turtle.Turtle() # w -> write
w.hideturtle()
w.pu()

while len(flags) > 0: # len(flags) -> posa pragmata exei mesa h lista mou
    w.clear() # svinei mono oti egrapse h deuteri xelona
    w.goto(-200,250)
    w.write("Score: "+ str(points) + "     Lives: "+ str(lives) + "     Hints: "+str(hints), font=("Arial", 20))
    t.reset()
    choice = random.choice(flags)
    #print(choice.__name__)
    choice()

    answer = input("Guess the flag: ").lower() # lower() -> kanw ola ta grammata mikra

    if answer == choice.__name__:
        print("Correct!")
        points += 1
        flags.remove(choice) # petaw tin simaia pou vrika apo tin lista
    else:
        print("Wrong!")
        lives -= 1

    if lives == 0:
        w.clear()
        w.write("I'm sorry! Out of lives! You lost!", font=("Arial", 20))
        break

if lives != 0:
    w.clear()
    w.write("Congrats! You won! Your final score is " + str(points), font=("Arial", 20))

turtle.done()